#!/usr/bin/env sh
# ──────────────────────────────────────────────────────────────────────────────
# DeviOpps — Full installer
# Sets up the dashboard (Docker + Postgres) AND downloads the worker agent.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/zgyant/devi-opps-worker/refs/heads/main/install.sh | sh
#   — or —
#   sh install.sh
# ──────────────────────────────────────────────────────────────────────────────
set -eu

# ── Config ────────────────────────────────────────────────────────────────────
REPO="zgyant/devi-opps-worker"
BRANCH="main"
BIN_DIR="worker"
BASE_URL="https://raw.githubusercontent.com/${REPO}/refs/heads/${BRANCH}/${BIN_DIR}"

APP_IMAGE="zayantmishra/devi-opps"
INSTALL_DIR="${DEVI_INSTALL_DIR:-$HOME/.devi-ops}"
APP_PORT="${PORT:-3000}"
DB_PORT="${DB_PORT:-5432}"
DB_USER="${DB_USER:-wait_what}"
DB_PASSWORD="${DB_PASSWORD:-wait_what}"
DB_NAME="${DB_NAME:-wait_what}"

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

# ── Helpers ───────────────────────────────────────────────────────────────────
log()   { printf "${GREEN}  ✓  ${NC}%s\n" "$1"; }
warn()  { printf "${YELLOW}  !  ${NC}%s\n" "$1"; }
error() { printf "${RED}  ✗  ${NC}%s\n" "$1"; exit 1; }
step()  { printf "\n${BLUE}${BOLD}──▶  ${NC}${BOLD}%s${NC}\n" "$1"; }

banner() {
  printf "\n${BLUE}${BOLD}"
  printf "   ██████╗ ███████╗██╗   ██╗██╗ ██████╗ ██████╗ ██████╗ ███████╗\n"
  printf "   ██╔══██╗██╔════╝██║   ██║██║██╔═══██╗██╔══██╗██╔══██╗██╔════╝\n"
  printf "   ██║  ██║█████╗  ██║   ██║██║██║   ██║██████╔╝██████╔╝███████╗\n"
  printf "   ██║  ██║██╔══╝  ╚██╗ ██╔╝██║██║   ██║██╔═══╝ ██╔═══╝ ╚════██║\n"
  printf "   ██████╔╝███████╗ ╚████╔╝ ██║╚██████╔╝██║     ██║     ███████║\n"
  printf "   ╚═════╝ ╚══════╝  ╚═══╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝     ╚══════╝\n"
  printf "${NC}\n"
  printf "   ${BOLD}Full Stack Installer${NC}  —  dashboard + worker agent\n\n"
}

# ══════════════════════════════════════════════════════════════════════════════
# PART 1 — Docker dashboard + Postgres
# ══════════════════════════════════════════════════════════════════════════════

check_docker() {
  step "Checking Docker"

  if ! command -v docker >/dev/null 2>&1; then
    error "Docker is not installed. Visit https://docs.docker.com/engine/install/"
  fi

  # Fedora ships Podman; the podman-docker shim exposes 'docker' but lacks
  # the Compose plugin this installer requires.
  if docker --version 2>/dev/null | grep -qi podman; then
    error "Podman detected as 'docker'. This installer requires Docker CE.\n  Install guide: https://docs.docker.com/engine/install/fedora/"
  fi

  log "Docker: $(docker --version | head -n1)"

  if ! docker info >/dev/null 2>&1; then
    if [ "$(id -u)" != "0" ] && ! id -nG 2>/dev/null | grep -qw docker; then
      error "Cannot connect to Docker daemon. Your user is not in the 'docker' group.\n  Fix: sudo usermod -aG docker \$USER && newgrp docker\n  Then re-run this script."
    fi
    error "Docker daemon is not running. Start it with: sudo systemctl start docker"
  fi
  log "Docker daemon is running"

  if docker compose version >/dev/null 2>&1; then
    COMPOSE="docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE="docker-compose"
  else
    error "Docker Compose not found.\n  Fedora/RHEL:    sudo dnf install docker-compose-plugin\n  Debian/Ubuntu:  sudo apt install docker-compose-plugin\n  Other:          https://docs.docker.com/compose/install/"
  fi
  log "Compose: $($COMPOSE version --short 2>/dev/null || printf 'found')"
}

check_ports() {
  step "Checking ports"
  for port in "$APP_PORT" "$DB_PORT"; do
    _port_used=0
    if command -v lsof >/dev/null 2>&1; then
      lsof -Pi ":$port" -sTCP:LISTEN -t >/dev/null 2>&1 && _port_used=1 || true
    elif command -v ss >/dev/null 2>&1; then
      # ss is the lsof alternative on Fedora / minimal Linux images
      ss -tlnp "sport = :${port}" 2>/dev/null | grep -q LISTEN && _port_used=1 || true
    fi
    if [ "$_port_used" -eq 1 ]; then
      warn "Port $port already in use — override with PORT= or DB_PORT="
    else
      log "Port $port is free"
    fi
  done
}

setup_directory() {
  step "Setting up install directory: $INSTALL_DIR"
  mkdir -p "$INSTALL_DIR"
  log "Directory ready"
}

pull_app_image() {
  step "Pulling app image: $APP_IMAGE"
  docker pull "$APP_IMAGE"
  log "App image ready"
}

write_compose() {
  step "Writing docker-compose.yaml"
  cat > "$INSTALL_DIR/docker-compose.yaml" << YAML
# Generated by DeviOpps installer — re-run install.sh to update
services:

  db:
    image: postgres:16
    container_name: devi-ops-db
    restart: always
    environment:
      POSTGRES_USER:     \${DB_USER:-wait_what}
      POSTGRES_PASSWORD: \${DB_PASSWORD:-wait_what}
      POSTGRES_DB:       \${DB_NAME:-wait_what}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "\${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${DB_USER:-wait_what}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: $APP_IMAGE
    container_name: devi-ops-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://\${DB_USER:-wait_what}:\${DB_PASSWORD:-wait_what}@db:5432/\${DB_NAME:-wait_what}
      NODE_ENV:     production
      HOST:         0.0.0.0
      PORT:         \${PORT:-3000}
    ports:
      - "\${PORT:-3000}:3000"

volumes:
  pgdata:
YAML
  log "docker-compose.yaml written"
}

write_env() {
  if [ -f "$INSTALL_DIR/.env" ]; then
    log ".env already exists — skipping (delete it to regenerate)"
    return
  fi
  step "Writing .env"
  cat > "$INSTALL_DIR/.env" << ENV
PORT=$APP_PORT
DB_PORT=$DB_PORT
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME
ENV
  log ".env created at $INSTALL_DIR/.env"
  warn "Update DB_PASSWORD before exposing to the internet"
}

start_services() {
  step "Starting Postgres + app (docker compose up -d)"
  cd "$INSTALL_DIR"
  $COMPOSE up -d
  log "Containers started"
}

wait_for_app() {
  step "Waiting for app to be ready"
  _max=30
  _n=0
  while [ "$_n" -lt "$_max" ]; do
    if command -v curl >/dev/null 2>&1 && curl -sf "http://localhost:${APP_PORT}/api/health" >/dev/null 2>&1; then
      log "App is healthy at http://localhost:${APP_PORT}"
      return 0
    fi
    _n=$((_n + 1))
    printf "."
    sleep 2
  done
  printf "\n"
  warn "App did not respond within 60s — may still be starting"
  warn "Check: cd $INSTALL_DIR && $COMPOSE logs -f app"
}

# ══════════════════════════════════════════════════════════════════════════════
# PART 2 — Worker agent binary
# ══════════════════════════════════════════════════════════════════════════════

select_worker_binary() {
  step "Select worker binary to download"

  # Auto-detect a sensible default
  _raw_os="$(uname -s 2>/dev/null | tr '[:upper:]' '[:lower:]')"
  _raw_arch="$(uname -m 2>/dev/null)"
  _default=1
  case "$_raw_os" in
    linux*)
      case "$_raw_arch" in
        x86_64|amd64)  _default=1 ;;
        arm64|aarch64) _default=2 ;;
      esac ;;
    darwin*)
      case "$_raw_arch" in
        x86_64|amd64)  _default=3 ;;
        arm64|aarch64) _default=4 ;;
      esac ;;
  esac

  printf "\n"
  printf "  ${BOLD}1)${NC} Linux   amd64  — most servers, x86_64 VMs\n"
  printf "  ${BOLD}2)${NC} Linux   arm64  — Raspberry Pi 4, AWS Graviton, Ampere\n"
  printf "  ${BOLD}3)${NC} macOS   amd64  — Intel Mac\n"
  printf "  ${BOLD}4)${NC} macOS   arm64  — Apple Silicon (M-series)\n"
  printf "\n"

  if [ ! -t 0 ]; then
    # Piped / non-interactive (e.g. curl | sh) — fall back to auto-detected default
    warn "Non-interactive mode — using auto-detected default: option $_default"
    _choice="$_default"
  else
    printf "  Auto-detected default: [${BOLD}%s${NC}]\n" "$_default"
    printf "  Enter selection [1-4] (press Enter to accept default): "
    read -r _choice </dev/tty || _choice=""
    [ -z "$_choice" ] && _choice="$_default"
  fi

  case "$_choice" in
    1) OS="linux";  ARCH="amd64" ;;
    2) OS="linux";  ARCH="arm64" ;;
    3) OS="darwin"; ARCH="amd64" ;;
    4) OS="darwin"; ARCH="arm64" ;;
    *) error "Invalid selection '$_choice' — enter a number between 1 and 4" ;;
  esac

  BINARY_NAME="deviopps-worker-${OS}-${ARCH}"
  WORKER_BIN="$INSTALL_DIR/worker"
  DOWNLOAD_URL="${BASE_URL}/${BINARY_NAME}"

  log "Selected: ${OS}/${ARCH}  →  $BINARY_NAME"
}

download_worker() {
  step "Downloading worker: $BINARY_NAME"
  printf "  URL: %s\n\n" "$DOWNLOAD_URL"

  if command -v curl >/dev/null 2>&1; then
    curl -fSL --progress-bar "$DOWNLOAD_URL" -o "$WORKER_BIN"
  elif command -v wget >/dev/null 2>&1; then
    wget -q --show-progress "$DOWNLOAD_URL" -O "$WORKER_BIN"
  else
    error "Neither curl nor wget found — cannot download worker binary"
  fi

  chmod +x "$WORKER_BIN"
  log "Worker binary saved to $WORKER_BIN"
}

# ══════════════════════════════════════════════════════════════════════════════
# Summary
# ══════════════════════════════════════════════════════════════════════════════

print_summary() {
  printf "\n${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
  printf "${GREEN}${BOLD}  DeviOpps is ready!${NC}\n"
  printf "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n\n"
  printf "  ${BOLD}Dashboard${NC}     http://localhost:${APP_PORT}\n"
  printf "  ${BOLD}Install dir${NC}   %s\n\n" "$INSTALL_DIR"
  printf "  ${YELLOW}${BOLD}Next — connect a worker to a remote host${NC}\n\n"
  printf "  Copy the worker to the target machine, then:\n\n"
  printf "  ${YELLOW}1.${NC} Run setup (generates credentials):\n"
  printf "     ${BOLD}./worker init${NC}\n\n"
  printf "  ${YELLOW}2.${NC} Register Worker ID + Token in the dashboard\n"
  printf "     Settings → Workers → Add Worker\n\n"
  printf "  ${YELLOW}3.${NC} Start the worker:\n"
  printf "     ${BOLD}./worker${NC}\n\n"
  printf "  ${BLUE}${BOLD}Dashboard commands${NC}\n"
  printf "  Logs    cd %s && %s logs -f\n" "$INSTALL_DIR" "$COMPOSE"
  printf "  Stop    cd %s && %s down\n" "$INSTALL_DIR" "$COMPOSE"
  printf "  Update  docker pull %s && cd %s && %s up -d\n\n" "$APP_IMAGE" "$INSTALL_DIR" "$COMPOSE"
}

# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

main() {
  banner
  check_docker
  check_ports
  setup_directory
  pull_app_image
  write_compose
  write_env
  start_services
  wait_for_app
  select_worker_binary
  download_worker
  print_summary
}

main "$@"
